"""followers

Revision ID: 4375ed1ac227
Revises: a2e6c24ef06a
Create Date: 2024-02-27 17:33:06.968032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4375ed1ac227'
down_revision = 'a2e6c24ef06a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
